version: 0.0
os: linux
files:
  - source: /app
    destination: /home/ec2-user/nodetest
hooks:
  BeforeInstall:
    - location: app/shells/before.sh
      timeout: 300
  AfterInstall:
    - location: app/shells/after.sh
      timeout: 300
