version: 0.0
os: linux
files:
  - source: /app
    destination: /home/ec2-user/nodetest
hooks:
  # AfterInstall:
  #   - location: before.sh
  #     timeout: 300
  ApplicationStart:
    - location: app/after.sh
      timeout: 300
