version: 0.2

phases:
  build:
    commands:
      - cp appspec.yml app/appspec.yml
      - cd app
      - npm install
      - rm -rf node_modules
  post_build:
    commands:
      - npm run build
      - npm install
artifacts:
  files:
    - '**/*'
  base-directory: app
