version: 0.2

phases:
  build:
    commands:
      - if [ -e /tmp/node_modules.tar ]; then tar xf /tmp/node_modules.tar; fi
      - cd app
      - npm install
  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - '**/*'
  base-directory: app
cache:
  paths:
    - /tmp/node_modules.tar
