version: '3'

services:
  app:
    build: .
    container_name: ${PRODUCTION_NAME}
    ports: # ポート接続
      - 8000:8000
    tty: true
    stdin_open: true
    command: [sh, -c, npm install && npm run dev]
    volumes: # mount workdir
      - ./app:/app
